export interface SurahGroundTruth {
  id: number;
  transliteration: string;
  juzNumber: number;
  verseCount: number;
  revelationType: "Meccan" | "Medinan";
  bismillah: boolean;
}

export const SURAH_GROUND_TRUTH: SurahGroundTruth[] = [
  { id: 1, transliteration: "Al-Fatiha", juzNumber: 1, verseCount: 7, revelationType: "Meccan", bismillah: true },
  { id: 2, transliteration: "Al-Baqarah", juzNumber: 1, verseCount: 286, revelationType: "Medinan", bismillah: true },
  { id: 3, transliteration: "Ali Imran", juzNumber: 3, verseCount: 200, revelationType: "Medinan", bismillah: true },
  { id: 4, transliteration: "An-Nisa", juzNumber: 4, verseCount: 176, revelationType: "Medinan", bismillah: true },
  { id: 5, transliteration: "Al-Maidah", juzNumber: 6, verseCount: 120, revelationType: "Medinan", bismillah: true },
  { id: 6, transliteration: "Al-Anam", juzNumber: 7, verseCount: 165, revelationType: "Meccan", bismillah: true },
  { id: 7, transliteration: "Al-Araf", juzNumber: 8, verseCount: 206, revelationType: "Meccan", bismillah: true },
  { id: 8, transliteration: "Al-Anfal", juzNumber: 9, verseCount: 75, revelationType: "Medinan", bismillah: true },
  { id: 9, transliteration: "At-Tawbah", juzNumber: 10, verseCount: 129, revelationType: "Medinan", bismillah: false },
  { id: 10, transliteration: "Yunus", juzNumber: 11, verseCount: 109, revelationType: "Meccan", bismillah: true },
  { id: 11, transliteration: "Hud", juzNumber: 11, verseCount: 123, revelationType: "Meccan", bismillah: true },
  { id: 12, transliteration: "Yusuf", juzNumber: 12, verseCount: 111, revelationType: "Meccan", bismillah: true },
  { id: 13, transliteration: "Ar-Ra'd", juzNumber: 13, verseCount: 43, revelationType: "Medinan", bismillah: true },
  { id: 14, transliteration: "Ibrahim", juzNumber: 13, verseCount: 52, revelationType: "Meccan", bismillah: true },
  { id: 15, transliteration: "Al-Hijr", juzNumber: 14, verseCount: 99, revelationType: "Meccan", bismillah: true },
  { id: 16, transliteration: "An-Nahl", juzNumber: 14, verseCount: 128, revelationType: "Meccan", bismillah: true },
  { id: 17, transliteration: "Al-Isra", juzNumber: 15, verseCount: 111, revelationType: "Meccan", bismillah: true },
  { id: 18, transliteration: "Al-Kahf", juzNumber: 15, verseCount: 110, revelationType: "Meccan", bismillah: true },
  { id: 19, transliteration: "Maryam", juzNumber: 16, verseCount: 98, revelationType: "Meccan", bismillah: true },
  { id: 20, transliteration: "Ta-Ha", juzNumber: 16, verseCount: 135, revelationType: "Meccan", bismillah: true },
  { id: 21, transliteration: "Al-Anbiya", juzNumber: 17, verseCount: 112, revelationType: "Meccan", bismillah: true },
  { id: 22, transliteration: "Al-Hajj", juzNumber: 17, verseCount: 78, revelationType: "Medinan", bismillah: true },
  { id: 23, transliteration: "Al-Muminun", juzNumber: 18, verseCount: 118, revelationType: "Meccan", bismillah: true },
  { id: 24, transliteration: "An-Nur", juzNumber: 18, verseCount: 64, revelationType: "Medinan", bismillah: true },
  { id: 25, transliteration: "Al-Furqan", juzNumber: 18, verseCount: 77, revelationType: "Meccan", bismillah: true },
  { id: 26, transliteration: "Ash-Shuara", juzNumber: 19, verseCount: 227, revelationType: "Meccan", bismillah: true },
  { id: 27, transliteration: "An-Naml", juzNumber: 19, verseCount: 93, revelationType: "Meccan", bismillah: true },
  { id: 28, transliteration: "Al-Qasas", juzNumber: 20, verseCount: 88, revelationType: "Meccan", bismillah: true },
  { id: 29, transliteration: "Al-Ankabut", juzNumber: 20, verseCount: 69, revelationType: "Meccan", bismillah: true },
  { id: 30, transliteration: "Ar-Rum", juzNumber: 21, verseCount: 60, revelationType: "Meccan", bismillah: true },
  { id: 31, transliteration: "Luqman", juzNumber: 21, verseCount: 34, revelationType: "Meccan", bismillah: true },
  { id: 32, transliteration: "As-Sajdah", juzNumber: 21, verseCount: 30, revelationType: "Meccan", bismillah: true },
  { id: 33, transliteration: "Al-Ahzab", juzNumber: 21, verseCount: 73, revelationType: "Medinan", bismillah: true },
  { id: 34, transliteration: "Saba", juzNumber: 22, verseCount: 54, revelationType: "Meccan", bismillah: true },
  { id: 35, transliteration: "Fatir", juzNumber: 22, verseCount: 45, revelationType: "Meccan", bismillah: true },
  { id: 36, transliteration: "Ya-Sin", juzNumber: 22, verseCount: 83, revelationType: "Meccan", bismillah: true },
  { id: 37, transliteration: "As-Saffat", juzNumber: 23, verseCount: 182, revelationType: "Meccan", bismillah: true },
  { id: 38, transliteration: "Sad", juzNumber: 23, verseCount: 88, revelationType: "Meccan", bismillah: true },
  { id: 39, transliteration: "Az-Zumar", juzNumber: 23, verseCount: 75, revelationType: "Meccan", bismillah: true },
  { id: 40, transliteration: "Ghafir", juzNumber: 24, verseCount: 85, revelationType: "Meccan", bismillah: true },
  { id: 41, transliteration: "Fussilat", juzNumber: 24, verseCount: 54, revelationType: "Meccan", bismillah: true },
  { id: 42, transliteration: "Ash-Shura", juzNumber: 25, verseCount: 53, revelationType: "Meccan", bismillah: true },
  { id: 43, transliteration: "Az-Zukhruf", juzNumber: 25, verseCount: 89, revelationType: "Meccan", bismillah: true },
  { id: 44, transliteration: "Ad-Dukhan", juzNumber: 25, verseCount: 59, revelationType: "Meccan", bismillah: true },
  { id: 45, transliteration: "Al-Jathiyah", juzNumber: 25, verseCount: 37, revelationType: "Meccan", bismillah: true },
  { id: 46, transliteration: "Al-Ahqaf", juzNumber: 26, verseCount: 35, revelationType: "Meccan", bismillah: true },
  { id: 47, transliteration: "Muhammad", juzNumber: 26, verseCount: 38, revelationType: "Medinan", bismillah: true },
  { id: 48, transliteration: "Al-Fath", juzNumber: 26, verseCount: 29, revelationType: "Medinan", bismillah: true },
  { id: 49, transliteration: "Al-Hujurat", juzNumber: 26, verseCount: 18, revelationType: "Medinan", bismillah: true },
  { id: 50, transliteration: "Qaf", juzNumber: 26, verseCount: 45, revelationType: "Meccan", bismillah: true },
  { id: 51, transliteration: "Adh-Dhariyat", juzNumber: 26, verseCount: 60, revelationType: "Meccan", bismillah: true },
  { id: 52, transliteration: "At-Tur", juzNumber: 27, verseCount: 49, revelationType: "Meccan", bismillah: true },
  { id: 53, transliteration: "An-Najm", juzNumber: 27, verseCount: 62, revelationType: "Meccan", bismillah: true },
  { id: 54, transliteration: "Al-Qamar", juzNumber: 27, verseCount: 55, revelationType: "Meccan", bismillah: true },
  { id: 55, transliteration: "Ar-Rahman", juzNumber: 27, verseCount: 78, revelationType: "Medinan", bismillah: true },
  { id: 56, transliteration: "Al-Waqiah", juzNumber: 27, verseCount: 96, revelationType: "Meccan", bismillah: true },
  { id: 57, transliteration: "Al-Hadid", juzNumber: 27, verseCount: 29, revelationType: "Medinan", bismillah: true },
  { id: 58, transliteration: "Al-Mujadila", juzNumber: 28, verseCount: 22, revelationType: "Medinan", bismillah: true },
  { id: 59, transliteration: "Al-Hashr", juzNumber: 28, verseCount: 24, revelationType: "Medinan", bismillah: true },
  { id: 60, transliteration: "Al-Mumtahanah", juzNumber: 28, verseCount: 13, revelationType: "Medinan", bismillah: true },
  { id: 61, transliteration: "As-Saf", juzNumber: 28, verseCount: 14, revelationType: "Medinan", bismillah: true },
  { id: 62, transliteration: "Al-Jumuah", juzNumber: 28, verseCount: 11, revelationType: "Medinan", bismillah: true },
  { id: 63, transliteration: "Al-Munafiqun", juzNumber: 28, verseCount: 11, revelationType: "Medinan", bismillah: true },
  { id: 64, transliteration: "At-Taghabun", juzNumber: 28, verseCount: 18, revelationType: "Medinan", bismillah: true },
  { id: 65, transliteration: "At-Talaq", juzNumber: 28, verseCount: 12, revelationType: "Medinan", bismillah: true },
  { id: 66, transliteration: "At-Tahrim", juzNumber: 28, verseCount: 12, revelationType: "Medinan", bismillah: true },
  { id: 67, transliteration: "Al-Mulk", juzNumber: 29, verseCount: 30, revelationType: "Meccan", bismillah: true },
  { id: 68, transliteration: "Al-Qalam", juzNumber: 29, verseCount: 52, revelationType: "Meccan", bismillah: true },
  { id: 69, transliteration: "Al-Haqqah", juzNumber: 29, verseCount: 52, revelationType: "Meccan", bismillah: true },
  { id: 70, transliteration: "Al-Maarij", juzNumber: 29, verseCount: 44, revelationType: "Meccan", bismillah: true },
  { id: 71, transliteration: "Nuh", juzNumber: 29, verseCount: 28, revelationType: "Meccan", bismillah: true },
  { id: 72, transliteration: "Al-Jinn", juzNumber: 29, verseCount: 28, revelationType: "Meccan", bismillah: true },
  { id: 73, transliteration: "Al-Muzzammil", juzNumber: 29, verseCount: 20, revelationType: "Meccan", bismillah: true },
  { id: 74, transliteration: "Al-Muddaththir", juzNumber: 29, verseCount: 56, revelationType: "Meccan", bismillah: true },
  { id: 75, transliteration: "Al-Qiyamah", juzNumber: 29, verseCount: 40, revelationType: "Meccan", bismillah: true },
  { id: 76, transliteration: "Al-Insan", juzNumber: 29, verseCount: 31, revelationType: "Medinan", bismillah: true },
  { id: 77, transliteration: "Al-Mursalat", juzNumber: 29, verseCount: 50, revelationType: "Meccan", bismillah: true },
  { id: 78, transliteration: "An-Naba", juzNumber: 30, verseCount: 40, revelationType: "Meccan", bismillah: true },
  { id: 79, transliteration: "An-Naziat", juzNumber: 30, verseCount: 46, revelationType: "Meccan", bismillah: true },
  { id: 80, transliteration: "Abasa", juzNumber: 30, verseCount: 42, revelationType: "Meccan", bismillah: true },
  { id: 81, transliteration: "At-Takwir", juzNumber: 30, verseCount: 29, revelationType: "Meccan", bismillah: true },
  { id: 82, transliteration: "Al-Infitar", juzNumber: 30, verseCount: 19, revelationType: "Meccan", bismillah: true },
  { id: 83, transliteration: "Al-Mutaffifin", juzNumber: 30, verseCount: 36, revelationType: "Meccan", bismillah: true },
  { id: 84, transliteration: "Al-Inshiqaq", juzNumber: 30, verseCount: 25, revelationType: "Meccan", bismillah: true },
  { id: 85, transliteration: "Al-Buruj", juzNumber: 30, verseCount: 22, revelationType: "Meccan", bismillah: true },
  { id: 86, transliteration: "At-Tariq", juzNumber: 30, verseCount: 17, revelationType: "Meccan", bismillah: true },
  { id: 87, transliteration: "Al-Ala", juzNumber: 30, verseCount: 19, revelationType: "Meccan", bismillah: true },
  { id: 88, transliteration: "Al-Ghashiyah", juzNumber: 30, verseCount: 26, revelationType: "Meccan", bismillah: true },
  { id: 89, transliteration: "Al-Fajr", juzNumber: 30, verseCount: 30, revelationType: "Meccan", bismillah: true },
  { id: 90, transliteration: "Al-Balad", juzNumber: 30, verseCount: 20, revelationType: "Meccan", bismillah: true },
  { id: 91, transliteration: "Ash-Shams", juzNumber: 30, verseCount: 15, revelationType: "Meccan", bismillah: true },
  { id: 92, transliteration: "Al-Layl", juzNumber: 30, verseCount: 21, revelationType: "Meccan", bismillah: true },
  { id: 93, transliteration: "Ad-Duha", juzNumber: 30, verseCount: 11, revelationType: "Meccan", bismillah: true },
  { id: 94, transliteration: "Ash-Sharh", juzNumber: 30, verseCount: 8, revelationType: "Meccan", bismillah: true },
  { id: 95, transliteration: "At-Tin", juzNumber: 30, verseCount: 8, revelationType: "Meccan", bismillah: true },
  { id: 96, transliteration: "Al-Alaq", juzNumber: 30, verseCount: 19, revelationType: "Meccan", bismillah: true },
  { id: 97, transliteration: "Al-Qadr", juzNumber: 30, verseCount: 5, revelationType: "Meccan", bismillah: true },
  { id: 98, transliteration: "Al-Bayyinah", juzNumber: 30, verseCount: 8, revelationType: "Medinan", bismillah: true },
  { id: 99, transliteration: "Az-Zalzalah", juzNumber: 30, verseCount: 8, revelationType: "Medinan", bismillah: true },
  { id: 100, transliteration: "Al-Adiyat", juzNumber: 30, verseCount: 11, revelationType: "Meccan", bismillah: true },
  { id: 101, transliteration: "Al-Qariah", juzNumber: 30, verseCount: 11, revelationType: "Meccan", bismillah: true },
  { id: 102, transliteration: "At-Takathur", juzNumber: 30, verseCount: 8, revelationType: "Meccan", bismillah: true },
  { id: 103, transliteration: "Al-Asr", juzNumber: 30, verseCount: 3, revelationType: "Meccan", bismillah: true },
  { id: 104, transliteration: "Al-Humazah", juzNumber: 30, verseCount: 9, revelationType: "Meccan", bismillah: true },
  { id: 105, transliteration: "Al-Fil", juzNumber: 30, verseCount: 5, revelationType: "Meccan", bismillah: true },
  { id: 106, transliteration: "Quraysh", juzNumber: 30, verseCount: 4, revelationType: "Meccan", bismillah: true },
  { id: 107, transliteration: "Al-Maun", juzNumber: 30, verseCount: 7, revelationType: "Meccan", bismillah: true },
  { id: 108, transliteration: "Al-Kawthar", juzNumber: 30, verseCount: 3, revelationType: "Meccan", bismillah: true },
  { id: 109, transliteration: "Al-Kafirun", juzNumber: 30, verseCount: 6, revelationType: "Meccan", bismillah: true },
  { id: 110, transliteration: "An-Nasr", juzNumber: 30, verseCount: 3, revelationType: "Medinan", bismillah: true },
  { id: 111, transliteration: "Al-Masad", juzNumber: 30, verseCount: 5, revelationType: "Meccan", bismillah: true },
  { id: 112, transliteration: "Al-Ikhlas", juzNumber: 30, verseCount: 4, revelationType: "Meccan", bismillah: true },
  { id: 113, transliteration: "Al-Falaq", juzNumber: 30, verseCount: 5, revelationType: "Meccan", bismillah: true },
  { id: 114, transliteration: "An-Nas", juzNumber: 30, verseCount: 6, revelationType: "Meccan", bismillah: true }
];
